In [2]:
import torch 
print(torch.__version__)

2.11.0


In [11]:
if torch.mps.is_available():
    print("MPS is available. You can use the GPU for computations.")
    print("Device count:", torch.mps.device_count())
else:
    print("MPS is not available. You will be using the CPU for computations.")

MPS is available. You can use the GPU for computations.
Device count: 1


## Creating Tensor

In [14]:
# using empty 
a = torch.empty(2,3)
print(a)

# In my case, idk why it is zero always
# Enpty function allocates memory for the specified shape

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [15]:
# check type
type(a)


torch.Tensor

In [16]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [17]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# using rand
torch.rand(2,3) # values between 0 and 1


tensor([[0.5877, 0.8704, 0.9208],
        [0.4838, 0.8585, 0.3657]])

In [21]:
# use of seed 
torch.manual_seed(100)
torch.rand(2,3) # values between 0 and 1

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [22]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [23]:
# using arange
torch.arange(0,10,2) # start, end, step

tensor([0, 2, 4, 6, 8])

In [24]:
# using linspace
torch.linspace(0,10,8) # start, end, number of points

tensor([ 0.0000,  1.4286,  2.8571,  4.2857,  5.7143,  7.1429,  8.5714, 10.0000])

In [25]:
# using eye
torch.eye(5) # identity matrix of size 5x5

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [26]:
# using full
torch.full((2,3), 7) # shape, fill value

tensor([[7, 7, 7],
        [7, 7, 7]])

## Tensor Shapes

In [28]:
x = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
x

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [29]:
x.shape

torch.Size([3, 3])

In [30]:
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [31]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [32]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [34]:
torch.rand_like(x)

NotImplementedError: "check_uniform_bounds" not implemented for 'Long'

In [41]:
torch.rand_like(x, dtype = torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356],
        [0.7118, 0.7876, 0.4183]])

## Tensor Data Types

In [36]:
x.dtype

torch.int64

In [37]:
# assigning data type
torch.tensor([1.0,2.0,3.0], dtype = torch.int32)


tensor([1, 2, 3], dtype=torch.int32)

In [38]:
torch.tensor([1,2,3],dtype = torch.float32)

tensor([1., 2., 3.])

In [39]:
# using to
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

## Mathematical operations

### 1. Scalar Operations

In [42]:
x = torch.rand(2,2)
x

tensor([[0.9014, 0.9969],
        [0.7565, 0.2239]])

In [45]:
# addition
x+2 
# subtraction
x-2
# multiplication
x*2
# division
x/2
# int division
(x*100)//3
# mod
(x*100)%3
# power
x**(1.5)

tensor([[0.8558, 0.9953],
        [0.6580, 0.1059]])

### 2. Element wise oprations

In [46]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.3023, 0.1784, 0.8238],
        [0.5557, 0.9770, 0.4440]])
tensor([[0.9478, 0.7445, 0.4892],
        [0.2426, 0.7003, 0.5277]])


In [47]:
# add
a+b
#subtract
a-b
# multiply
a*b
# divide
a/b
# power
a**b
#mod 
a%b 

tensor([[0.3023, 0.1784, 0.3346],
        [0.0706, 0.2767, 0.4440]])

In [48]:
c = torch.tensor([1,-2,3,-4])


In [49]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [50]:
#negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [51]:
d = torch.tensor([1.9,-2.5,3.7,-4.1])

In [52]:
# round
torch.round(d)

tensor([ 2., -2.,  4., -4.])

In [53]:
# ceil
torch.ceil(d)

tensor([ 2., -2.,  4., -4.])

In [54]:
# floor
torch.floor(d)

tensor([ 1., -3.,  3., -5.])

In [55]:
# clamp 
torch.clamp(d, min = -2, max = 2)

tensor([ 1.9000, -2.0000,  2.0000, -2.0000])

### 3. reduction operations

In [57]:
e = torch.randint(size=(2,3), low=0, high=10)
e

tensor([[9, 4, 0],
        [5, 7, 5]])

In [59]:
# sum
e.sum()
torch.sum(e)

tensor(30)

In [61]:
# sum along the columns
torch.sum(e, dim=0)
# sum along the rows
torch.sum(e, dim=1)

tensor([13, 17])

In [65]:
# mean
torch.mean(e.float()) 
# mean along the columns
torch.mean(e.float(), dim=0)
# mean along the rows
torch.mean(e.float(), dim=1)

tensor([4.3333, 5.6667])

In [67]:
# median 
torch.median(e.float())
# max and min
torch.max(e)
torch.min(e)

tensor(0)

In [68]:
# product
torch.prod(e)

tensor(0)

In [69]:
# standard deviation
torch.std(e.float())

tensor(3.0332)

In [70]:
# variance
torch.var(e.float())

tensor(9.2000)

In [71]:
# argmax and argmin
torch.argmax(e)
torch.argmin(e)

tensor(2)

### 4. Matrix Operations

In [73]:
f = torch.randint(size=(2,3), low=0, high=10, dtype = torch.float32)
g = torch.randint(size=(3,2), low=0, high=10, dtype = torch.float32)

In [74]:
# matrix multiplication
torch.matmul(f,g)

tensor([[91., 48.],
        [74., 43.]])

In [75]:
# dot product
torch.dot(f.flatten(), g.flatten())

tensor(113.)

In [77]:
# transpose
torch.transpose(f, 0, 1)

tensor([[7., 6.],
        [8., 1.],
        [3., 5.]])

In [79]:
# determinant
torch.det(torch.rand(3,3))
# inverse
torch.inverse(torch.rand(3,3))

tensor([[-0.7739,  1.6215, -0.0998],
        [ 0.1216, -0.3843,  1.1589],
        [ 1.3048, -0.4088, -0.2635]])

### 5. Comparision operation

In [81]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)
print(i)
print(j)

tensor([[9, 2, 3],
        [1, 0, 2]])
tensor([[1, 2, 7],
        [9, 2, 4]])


In [84]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than or equal to
i >= j
# less than or equal to
i <= j

tensor([[False,  True,  True],
        [ True,  True,  True]])

### 6. Special Functions

In [87]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)

In [88]:
# log
torch.log(k)
# exp
torch.exp(k)
# sqrt
torch.sqrt(k)
#sigmoid
torch.sigmoid(k)
#softmax
torch.softmax(k, dim=0)
# ReLU
torch.relu(k)


tensor([[7., 9., 2.],
        [7., 0., 2.]])

## Inplace Operations

In [89]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.2732, 0.3397, 0.1879],
        [0.5534, 0.2682, 0.9556]])
tensor([[0.9761, 0.5934, 0.3124],
        [0.9431, 0.8519, 0.9815]])


In [90]:
m+n 

tensor([[1.2494, 0.9331, 0.5003],
        [1.4965, 1.1200, 1.9371]])

In [91]:
m.add_(n)

tensor([[1.2494, 0.9331, 0.5003],
        [1.4965, 1.1200, 1.9371]])

In [92]:
m

tensor([[1.2494, 0.9331, 0.5003],
        [1.4965, 1.1200, 1.9371]])

In [93]:
n

tensor([[0.9761, 0.5934, 0.3124],
        [0.9431, 0.8519, 0.9815]])

In [94]:
torch.relu(m)

tensor([[1.2494, 0.9331, 0.5003],
        [1.4965, 1.1200, 1.9371]])

In [95]:
m.relu_()

tensor([[1.2494, 0.9331, 0.5003],
        [1.4965, 1.1200, 1.9371]])

## Copying a Tensor

In [96]:
a = torch.rand(2,3)
a

tensor([[0.1132, 0.4783, 0.4436],
        [0.3847, 0.4521, 0.5569]])

In [98]:
b = a
b

tensor([[0.1132, 0.4783, 0.4436],
        [0.3847, 0.4521, 0.5569]])

In [99]:
a[0,0] = 100
a

tensor([[100.0000,   0.4783,   0.4436],
        [  0.3847,   0.4521,   0.5569]])

In [100]:
b

tensor([[100.0000,   0.4783,   0.4436],
        [  0.3847,   0.4521,   0.5569]])

In [101]:
id(a)

4815921200

In [102]:
id(b)

4815921200

In [103]:
b = a.clone()
b

tensor([[100.0000,   0.4783,   0.4436],
        [  0.3847,   0.4521,   0.5569]])

In [106]:
a[0,0] = 0
a

tensor([[0.0000, 0.4783, 0.4436],
        [0.3847, 0.4521, 0.5569]])

In [107]:
b

tensor([[100.0000,   0.4783,   0.4436],
        [  0.3847,   0.4521,   0.5569]])

In [108]:
id(a), id(b)

(4815921200, 4816411040)

## Tensor Operations on GPU (MPS)

In [4]:
torch.mps.is_available()

True

In [5]:
device = torch.device("mps") if torch.mps.is_available() else torch.device("cpu")
device

device(type='mps')

In [111]:
# Creating new tensor on GPU/MPS
torch.rand(2,3, device=device)

tensor([[0.4643, 0.8532, 0.4872],
        [0.4602, 0.4261, 0.0968]], device='mps:0')

In [114]:
# moving an existing tensor to GPU/MPS
x = torch.rand(2,3)
print(x)
b = x.to(device)

tensor([[0.2269, 0.7555, 0.6458],
        [0.3673, 0.1770, 0.2966]])


In [115]:
b + 5

tensor([[5.2269, 5.7555, 5.6458],
        [5.3673, 5.1770, 5.2966]], device='mps:0')

In [6]:
import time
size = 10000

# CPU
Matrix1_CPU = torch.randn(size, size)
Matrix2_CPU = torch.randn(size, size)

# Time on CPU 
start_time = time.time()
result_CPU = torch.matmul(Matrix1_CPU, Matrix2_CPU)
end_time = time.time()
print(f"Time taken on CPU: {end_time - start_time:.4f} seconds")

# GPU/MPS
matrix1_MPS = Matrix1_CPU.to(device)
matrix2_MPS = Matrix2_CPU.to(device)

# Time on GPU/MPS
start_time = time.time()
result_MPS = torch.matmul(matrix1_MPS, matrix2_MPS)
end_time = time.time()
print(f"Time taken on GPU/MPS: {end_time - start_time:.4f} seconds")

Time taken on CPU: 2.6139 seconds
Time taken on GPU/MPS: 0.1815 seconds


## Reshaping Tensors

In [7]:
a = torch.ones(4, 4)

In [8]:
# reshape 
a.reshape(2,8)

tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])

In [9]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
b = torch.rand(2,3,4)
b

tensor([[[0.4170, 0.4016, 0.0570, 0.5013],
         [0.4865, 0.9065, 0.9002, 0.6112],
         [0.0583, 0.6135, 0.1753, 0.1776]],

        [[0.4353, 0.7355, 0.4940, 0.7031],
         [0.9025, 0.7624, 0.0839, 0.5287],
         [0.6461, 0.5232, 0.0482, 0.7791]]])

In [11]:
# permute
b.permute(2,0,1)

tensor([[[0.4170, 0.4865, 0.0583],
         [0.4353, 0.9025, 0.6461]],

        [[0.4016, 0.9065, 0.6135],
         [0.7355, 0.7624, 0.5232]],

        [[0.0570, 0.9002, 0.1753],
         [0.4940, 0.0839, 0.0482]],

        [[0.5013, 0.6112, 0.1776],
         [0.7031, 0.5287, 0.7791]]])

In [18]:
# unsqueeze
c = torch.rand(266,266,3)
c.unsqueeze(0).shape

torch.Size([1, 266, 266, 3])

In [20]:
# Squeeze
d = torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

## Numpy and PyTorch

In [21]:
import numpy as np

In [22]:
a = torch.tensor([1,2,3])
a 

tensor([1, 2, 3])

In [24]:
b = a.numpy()

In [26]:
type(b)

numpy.ndarray

In [28]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [31]:
torch.from_numpy(c)

tensor([1, 2, 3])