In [1]:
import torch 

In [3]:
x = torch.tensor([3.0], requires_grad=True)
y = x**2 


In [4]:
print(y)
print(x)

tensor([9.], grad_fn=<PowBackward0>)
tensor([3.], requires_grad=True)


In [5]:
y.backward()

In [6]:
x.grad

tensor([6.])

In [7]:
x = torch.tensor([3.0], requires_grad=True)
y = x**2
z = torch.sin(y)

In [8]:
x,y,z

(tensor([3.], requires_grad=True),
 tensor([9.], grad_fn=<PowBackward0>),
 tensor([0.4121], grad_fn=<SinBackward0>))

In [9]:
z.backward()

In [11]:
print(x.grad)

tensor([-5.4668])


In [12]:
x = torch.tensor(6.7)
y = torch.tensor(0.0)

w = torch.tensor(1.0)
b = torch.tensor(0.0)

In [13]:
def binary_cross_entropy_loss(prediction, target):
    epsilon = 1e-7  # To prevent log(0)
    prediction = torch.clamp(prediction, epsilon, 1 - epsilon)  # Clamp predictions to avoid log(0)
    loss = - (target * torch.log(prediction) + (1 - target) * torch.log(1 - prediction))
    return loss

In [14]:
# forward pass
z = w * x + b
y_pred = torch.sigmoid(z)
loss = binary_cross_entropy_loss(y_pred, y)

In [15]:
loss

tensor(6.7012)

In [16]:
x = torch.tensor(6.7)
y = torch.tensor(0.0)

w = torch.tensor(1.0, requires_grad=True)
b = torch.tensor(0.0, requires_grad=True)

In [18]:
z = w * x + b
y_pred = torch.sigmoid(z)
loss = binary_cross_entropy_loss(y_pred, y)
loss

tensor(6.7012, grad_fn=<NegBackward0>)

In [19]:
loss.backward()

In [20]:
w.grad, b.grad

(tensor(6.6918), tensor(0.9988))

In [22]:
x = torch.tensor([1.0,2.0,3.0], requires_grad=True)
y = (x**2).mean()
y


tensor(4.6667, grad_fn=<MeanBackward0>)

In [23]:
y.backward()

In [24]:
x.grad

tensor([0.6667, 1.3333, 2.0000])

In [37]:
# clearing gradients
x = torch.tensor([1.0], requires_grad=True)


In [52]:
y = x**2
y

tensor([1.], grad_fn=<PowBackward0>)

In [53]:
y.backward()

In [54]:
x.grad

tensor([2.])

In [55]:
x.grad.zero_()

tensor([0.])

In [56]:
# disable gradient tracking
x = torch.tensor(2.0, requires_grad=True)
x

tensor(2., requires_grad=True)

In [57]:
y = x**2
y 

tensor(4., grad_fn=<PowBackward0>)

In [58]:
y.backward()

In [59]:
# Option 1 - using requires_grad_(False)
# Option 2 - detach()
# Option 3 - using torch.no_grad() context manager

In [60]:
x.requires_grad_(False)

tensor(2.)

In [61]:
y.backward()

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

In [62]:
x = torch.tensor(2.0, requires_grad=True)

z = x.detach()

In [64]:
y = x**2
y


tensor(4., grad_fn=<PowBackward0>)

In [65]:
y1 = z**2
y1

tensor(4.)

In [70]:
x = torch.tensor([2.5], requires_grad=True)

In [71]:
with torch.no_grad():
    y = x**2
    print(y)

tensor([6.2500])


In [73]:
y.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn